name: MineLC_Lobby
main: com.minelc.LOBBY.LobbyMain
authors: [Leo018, obed_007, ElBuenAnvita]
version: 1.3.18
depend: [ScoreboardLib]
commands:
  minelc:
    description: Comando del servidor.
  mem:
    description: memoria libre
  tpworld:
    description: memoria libre
  bc:
    description: Usea parabloquear comandos
    usage: /ac <Command>
    permission: ac.add
  vippay:
    description: Envía VIP-Points a un amigo o compañero
    aliases: [pay, payvip, enviar]