KillBungeeMobsOnStop: false
ShowPingErrorInConsole: true
ItemGoBack: "340:0"
Messages:
  Conecting: "&aConecting with <ServerName>.."
  ConnectError: "&4Error when trying to connect to <ServerName>"
  GamesInProgress: "&eJuegos en progreso" # &eGames in progress
  InvTitleProgress: "&eProgreso" # &eProgress
  MenuGoBack: "&cAtrás" #&cGo Back

Location:
  world: "world"
  x: "-920.5"
  y: "158"
  z: "684.5"
  pitch: "180"
  yaw: "-11"

version-yml: 'v1.3'

permisos:
  default:
    - "jumppads.use"
    - "trail.allow"
    - "trail.heart"
    - "trail.angry"
    - "trail.magic"
    - "trail.fun"
    - "playeroptions.visibility"
    - "playeroptions.doublejump"
    - "playeroptions.chat"
    - "playeroptions.speed"
    - "playeroptions.use"
    - "settings.doublejump"
    - "settings.chat"
    - "settings.speed"
  vip:
    - "prodigy.particle.*"
    - "playeroptions.stacker"
    - "playeroptions.jump"
    - "settings.stacker"
    - "settings.jump"
    - "trail.cloud"
    - "trail.wmagic"
    - "trail.ender"
    - "trail.green"
    - "trail.spark"
    - "trail.flame"
    - "trail.white"
    - "trail.rain.tear"
  svip:
    - "settings.fly"
    - "playeroptions.fly"
    - "trail.water"
    - "trail.note"
    - "trail.snow"
    - "trail.lava"
    - "trail.crit"
    - "trail.smoke"
    - "trail.spell"
    - "trail.enchant"
    - "trail.splash"
    - "trail.block.rainbow"
    - "trail.block.carpet"
    - "trail.block.redstone"
    - "trail.rain.blood"
    - "trail.rain.dia"
    - "trail.rain.builder"
    - "trail.limit.vip"
    - "trail.limit.bypass"
  elite:
    - "prodigy.morph.*"
    - "prodigy.mood.*"
    - "echopet.pet.type.magmacube"
    - "echopet.pet.type.guardian"
    - "echopet.pet.type.Blaze"
    - "echopet.pet.type.enderman"
    - "trail.slime"
    - "trail.snowball"
    - "trail.void"
    - "trail.pop"
    - "trail.rainbow"
    - "trail.breath"
    - "trail.endrod"
    - "trail.damage"
    - "trail.sand"
    - "trail.totem"
    - "trail.block.sea"
    - "trail.block.wheat"
    - "trail.block.ore"
    - "trail.block.clay"
    - "trail.rain.wart"
    - "trail.rain.gold"
    - "trail.rain.builder"
    - "trail.limit.vip"
    - "trail.wing.bf"
    - "trail.limit.bypass"
    - "trail.wings"
    - "trail.wing.angel"
  ruby:
    - "prodigy.suit.*"
    - "prodigy.morph.*"
    - "prodigy.minion.*"
    - "trail.block.flower"
    - "echopet.pet.type.irongolem"
    - "echopet.pet.type.wither"
    - "customwings.command"
    - "customwings.wing.SoulShadow"
    - "playeroptions.visibility.vip"
  ayudante:
    - "prodigy.gadget.*"
    - "prodigy.pet.*"
    - "prodigy.particle.*"
    - "prodigy.suit.*"
    - "prodigy.morph.*"
    - "prodigy.minion.*"
    - "playeroptions.visibility.vip"
  mod:
    - "echopet.pet.type.snowman"
    - "echopet.pet.type.horse"
    - "customwings.command"
    - "customwings.wing.BloodHound"
    - "customwings.wing.SoulShadow"
    - "playeroptions.visibility.vip"
  admin:
    - "jumppads.maxpower.bypass"
    - "jumppads.create"
    - "jumppads.delete"
    - "jumppads.set"
    - "jumppads.delete"
    - "jumppads.reload"
    - "echopet.pet.type.wither"
    - "echopet.pet.type.irongolem"
    - "customwings.wing.Frost"
    - "playeroptions.visibility.vip"
  owner:
    - "echopet.pet.*"
    - "customwings.Wisdom"
    - "customwings.reload"
    - "customwings.setwing"
    - "playeroptions.visibility.vip"
    - "bukkit.*"
    - "minecraft.*"
    - "*"

scoreboard:
  title: "&6&lMineLC &3&lNetwork"
  content:
    - '&7&m+----------------+'
    - '&8» &fNick: &7$player$'
    - '&7    '
    - '&8» &fLCoins: &6%lc_lccoins% ⛁'
    - '&8» &fVIP-Points: &b%lc_vippoints% Ⓥ'
    - '&7   '
    - '&8» &fRango: %lc_rankcolorsignorehidden%'
    - '&8» &fDuración: &a$duration$'
    - '&7  '
    - '&8» &eplay.minelc.net'
    - '&7&m+-----------------+'

welcome:
  - "&6&l================================"
  - ""
  - "&e        Bienvenido &6$player$&e a"
  - "              &3&lMineLC &6&lNetwork"
  - ""
  - "&f&l                  Sitio Web:"
  - "              &bhttps://www.minelc.net/"
  - ""
  - "&9&l                 Discord:"
  - "&b              discord.minelc.net"
  - ""
  - "&f&l Compra los mejores rangos en:"
  - "           &btienda.minelc.net"
  - ""
  - "&6&l================================"

tienda:
  vip:
    7d:
      precio: 'USD $0.90'
      vippoints: 100
    15d:
      precio: 'USD $2.10'
      vippoints: 250
    30d:
      precio: 'USD $3.30'
      vippoints: 400
  svip:
    7d:
      precio: 'USD $2.70'
      vippoints: 270
    15d:
      precio: 'USD $3.60'
      vippoints: 460
    30d:
      precio: 'USD $7.20'
      vippoints: 600
  elite:
    7d:
      precio: 'USD $3.00'
      vippoints: 450
    15d:
      precio: 'USD $4.80'
      vippoints: 700
    30d:
      precio: 'USD $10.80'
      vippoints: 1100
  ruby:
    7d:
      precio: 'USD $6.00'
      vippoints: 600
    15d:
      precio: 'USD $10.80'
      vippoints: 1300
    30d:
      precio: 'USD $18.00'
      vippoints: 1600

items:
  modalidades:
    survival:
      title: "&6&k||&aSurvival&6&k||"
      lore:
        - "&8&m-----------------------------------"
        - "&fUn survival con parcelas, economía,"
        - "&fmundo PvP, tiendas, eventos y muchas"
        - "&fotras cosas más para asegurar tu diversión"
        - "&8&m-----------------------------------"
        - "   "
        - "&6¡Hay %online% jugadores conectados!"
        - " "
        - "&eClick para ingresar"
    creativo:
      title: "&6&k||&aCreativo&6&k||"
      lore:
        - "&8&m-----------------------------------"
        - "&fDemuestra tus habilidades como constructor,"
        - "&frolea, y pásala bien con todos en esta modalidad"
        - "&fLa imaginación es tu límite."
        - "&8&m-----------------------------------"
        - "   "
        - "&6¡Hay %online% jugadores conectados!"
        - " "
        - "&eClick para ingresar"
    eggwars:
      title: "&6&k||&aEggWars&6&k||"
      lore:
        - "&8&m-----------------------------------"
        - "&fDestruye los huevos enemigos para ganar,"
        - "&fprotege el tuyo para poder reaparecer"
        - "&fcompra mejoras y utiles objetos para lograr"
        - "&ftu acometido y ganar la partida!"
        - "&8&m-----------------------------------"
        - "   "
        - "&6¡Hay %online% jugadores conectados!"
        - " "
        - "&eClick para ingresar"
    chg:
      title: "&6&k||&aHG Clásicos&6&k||"
      lore:
        - "&8&m-----------------------------------"
        - "&fJuegos del Hambre, como siempre lo has conocido"
        - "&fMata a todos los jugadores y sé el último hombre"
        - "&fen pie para poder ganar."
        - "&8&m-----------------------------------"
        - "   "
        - "&6¡Hay %online% jugadores conectados!"
        - " "
        - "&eClick para ingresar"
    pvpgames:
      title: "&6&k||&aPvPGames&6&k||"
      lore:
        - "&8&m-----------------------------------"
        - "&fEntra y disfruta de una variedad de juegos"
        - "&fDiviértete con tus amigos, jugando a alguno"
        - "&fde estos juegos"
        - "&8&m-----------------------------------"
        - ""
        - "&6¡Hay %online% jugadores conectados!"
        - " "
        - "&eClick para ingresar"
    kitpvp:
      title: "&6&k||&aKitPvP&6&k||"
      lore:
        - "&8&m-----------------------------------"
        - "&fDemuestra tus habilidades en PvP aquí"
        - "&fUsa un kit, personalízalo a tu gusto a"
        - "&f medida que avanzas, ¡y sal a la batalla!"
        - "&8&m-----------------------------------"
        - ""
        - "&6¡Hay %online% jugadores conectados!"
        - " "
        - "&eClick para ingresar"
    skywars:
      title: "&6&k||&aSkyWars&6&k||"
      lore:
        - "&8&m-----------------------------------"
        - "&fSaquea sus cofres y viaja al centro del"
        - "&fmapa para luchar contra otros jugadores"
        - "&fo conseguir un mejor botín. Mata a los demás"
        - "&fy sé el último equipo o jugador en pie"
        - "&8&m-----------------------------------"
        - ""
        - "&6¡Hay %online% jugadores conectados!"
        - ""
        - "&eClick para ingresar"
    practice:
      title: "&6&k||&aPractice&6&k||"
      lore:
        - "&8&m-----------------------------------"
        - "&fPractica tus habilidades de PvP con un"
        - "&fkit personalizado. En tu modo de arena"
        - "&fde preferencia. Duela a los demás y gana"
        - "&frecompensas de los eventos"
        - "&8&m-----------------------------------"
        - ""
        - "&6¡Hay %online% jugadores conectados!"
        - ""
        - "&eClick para ingresar"
    skyblock:
      title: "&6&k||&aSkyBlock&6&k||"
      lore:
        - "&8&m-----------------------------------"
        - "&7&o¿Qué tenemos, un viajero del tiempo?"
        - "&cModalidad en construcción"
        - "&8&m-----------------------------------"

social-media:
  facebook:
    username: ''
    link: 'mine.lc/facebook'
    lines:
      - "&6&m----------------------------------"
      - "&fComunicate con nosotros vía Facebook"
      - "&fEnterate de las novedades, información y publicaciones"
      - "&frelacionadas con el servidor en:"
      - "&cEsto estará muy pronto."
      - "&6&m----------------------------------"
  twitter:
    username: '@MineLCNetwork'
    link: 'mine.lc/twitter'
    lines:
      - "&6&m----------------------------------"
      - "&f¡Síguenos en Twitter!"
      - "&fParticipa de sorteos, eventos y"
      - "&fentérate de las actualizaciones"
      - "&b@MineLCNetwork &7| &b&nmine.lc/twitter"
      - "&6&m----------------------------------"
  discord:
    link: 'mine.lc/discord'
    lines:
      - "&6&m----------------------------------"
      - "&f¡Forma parte de nuestro servidor de Discord!"
      - "&7Juega con amigos, comparte con la comunidad,"
      - "&7haz reportes, y obtén las últimasn novedades"
      - "&7y más...!"
      - "&a¡Entra ya! &7| &5&nmine.lc/discord"
      - "&6&m----------------------------------"
  forum:
    link: 'mine.lc/foro'
    lines:
      - "&6&m----------------------------------"
      - "&fVisita nuestro Foro Oficial"
      - "&7Reporta usuarios ilegales, comparte tus ideas,"
      - "&7haz reportes, y obtén las últimas novedades"
      - "&aForo &7| &7&nmine.lc/foro"
      - "&6&m----------------------------------"